Add more debug prints

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -66,7 +66,11 @@ runs:
             echo "Running ${{ inputs.compile-command }} $file"
             ${{ inputs.compile-command }} "$file" \
               && (echo "$file" >> "${{ inputs.success-list}}") \
-              || (echo "$file" >> "${{ inputs.current-failure-list}}")
+              || (echo "$file" >> "${{ inputs.current-failure-list }}")
+            echo "Current success list:"
+            cat "${{ inputs.success-list}}"
+            echo "Current failure list:"
+            cat "${{ inputs.current-failure-list }}"
           done <"${{ inputs.failure-list }}"
         done
         echo 'Done.'
